package de.shks.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import de.shks.example.demo.entities.Country;
import de.shks.example.demo.repositories.CountryRepository;

@Component
public class CountryDataInitializer implements ApplicationRunner{
    @Autowired
    CountryRepository repository;

    @Override
    public void run(ApplicationArguments args) throws Exception {
        
        repository.save( new Country( "Afghanistan", "AF", "AFG", "Kabul", "Asia", "Southern Asia", 27657145L, "https://restCountry.eu/data/afg.svg", "Asia") );
        repository.save( new Country( "Ã…land Islands", "AX", "ALA", "Mariehamn", "Europe", "Northern Europe", 28875L, "https://restCountry.eu/data/ala.svg", "Europe") );
        repository.save( new Country( "Albania", "AL", "ALB", "Tirana", "Europe", "Southern Europe", 2886026L, "https://restCountry.eu/data/alb.svg", "Europe") );
        repository.save( new Country( "Algeria", "DZ", "DZA", "Algiers", "Africa", "Northern Africa", 40400000L, "https://restCountry.eu/data/dza.svg", "Africa") );
        repository.save( new Country( "American Samoa", "AS", "ASM", "Pago Pago", "Oceania", "Polynesia", 57100L, "https://restCountry.eu/data/asm.svg", "Oceania") );
        repository.save( new Country( "Andorra", "AD", "AND", "Andorra la Vella", "Europe", "Southern Europe", 78014L, "https://restCountry.eu/data/and.svg", "Europe") );
        repository.save( new Country( "Angola", "AO", "AGO", "Luanda", "Africa", "Middle Africa", 25868000L, "https://restCountry.eu/data/ago.svg", "Africa") );
        repository.save( new Country( "Anguilla", "AI", "AIA", "The Valley", "Americas", "Caribbean", 13452L, "https://restCountry.eu/data/aia.svg", "Americas") );
        repository.save( new Country( "Antarctica", "AQ", "ATA", "", "Polar", "", 1000L, "https://restCountry.eu/data/ata.svg", "Polar") );
        repository.save( new Country( "Antigua and Barbuda", "AG", "ATG", "Saint John's", "Americas", "Caribbean", 86295L, "https://restCountry.eu/data/atg.svg", "Americas") );
        repository.save( new Country( "Argentina", "AR", "ARG", "Buenos Aires", "Americas", "South America", 43590400L, "https://restCountry.eu/data/arg.svg", "Americas") );
        repository.save( new Country( "Armenia", "AM", "ARM", "Yerevan", "Asia", "Western Asia", 2994400L, "https://restCountry.eu/data/arm.svg", "Asia") );
        repository.save( new Country( "Aruba", "AW", "ABW", "Oranjestad", "Americas", "Caribbean", 107394L, "https://restCountry.eu/data/abw.svg", "Americas") );
        repository.save( new Country( "Australia", "AU", "AUS", "Canberra", "Oceania", "Australia and New Zealand", 24117360L, "https://restCountry.eu/data/aus.svg", "Oceania") );
        repository.save( new Country( "Austria", "AT", "AUT", "Vienna", "Europe", "Western Europe", 8725931L, "https://restCountry.eu/data/aut.svg", "Europe") );
        repository.save( new Country( "Azerbaijan", "AZ", "AZE", "Baku", "Asia", "Western Asia", 9730500L, "https://restCountry.eu/data/aze.svg", "Asia") );
        repository.save( new Country( "Bahamas", "BS", "BHS", "Nassau", "Americas", "Caribbean", 378040L, "https://restCountry.eu/data/bhs.svg", "Americas") );
        repository.save( new Country( "Bahrain", "BH", "BHR", "Manama", "Asia", "Western Asia", 1404900L, "https://restCountry.eu/data/bhr.svg", "Asia") );
        repository.save( new Country( "Bangladesh", "BD", "BGD", "Dhaka", "Asia", "Southern Asia", 161006790L, "https://restCountry.eu/data/bgd.svg", "Asia") );
        repository.save( new Country( "Barbados", "BB", "BRB", "Bridgetown", "Americas", "Caribbean", 285000L, "https://restCountry.eu/data/brb.svg", "Americas") );
        repository.save( new Country( "Belarus", "BY", "BLR", "Minsk", "Europe", "Eastern Europe", 9498700L, "https://restCountry.eu/data/blr.svg", "Europe") );
        repository.save( new Country( "Belgium", "BE", "BEL", "Brussels", "Europe", "Western Europe", 11319511L, "https://restCountry.eu/data/bel.svg", "Europe") );
        repository.save( new Country( "Belize", "BZ", "BLZ", "Belmopan", "Americas", "Central America", 370300L, "https://restCountry.eu/data/blz.svg", "Americas") );
        repository.save( new Country( "Benin", "BJ", "BEN", "Porto-Novo", "Africa", "Western Africa", 10653654L, "https://restCountry.eu/data/ben.svg", "Africa") );
        repository.save( new Country( "Bermuda", "BM", "BMU", "Hamilton", "Americas", "Northern America", 61954L, "https://restCountry.eu/data/bmu.svg", "Americas") );
        repository.save( new Country( "Bhutan", "BT", "BTN", "Thimphu", "Asia", "Southern Asia", 775620L, "https://restCountry.eu/data/btn.svg", "Asia") );
        repository.save( new Country( "Bolivia (Plurinational State of)", "BO", "BOL", "Sucre", "Americas", "South America", 10985059L, "https://restCountry.eu/data/bol.svg", "Americas") );
        repository.save( new Country( "Bonaire, Sint Eustatius and Saba", "BQ", "BES", "Kralendijk", "Americas", "Caribbean", 17408L, "https://restCountry.eu/data/bes.svg", "Americas") );
        repository.save( new Country( "Bosnia and Herzegovina", "BA", "BIH", "Sarajevo", "Europe", "Southern Europe", 3531159L, "https://restCountry.eu/data/bih.svg", "Europe") );
        repository.save( new Country( "Botswana", "BW", "BWA", "Gaborone", "Africa", "Southern Africa", 2141206L, "https://restCountry.eu/data/bwa.svg", "Africa") );
        repository.save( new Country( "Bouvet Island", "BV", "BVT", "", "", "", 0L, "https://restCountry.eu/data/bvt.svg", "") );
        repository.save( new Country( "Brazil", "BR", "BRA", "BrasÃ­lia", "Americas", "South America", 206135893L, "https://restCountry.eu/data/bra.svg", "Americas") );
        repository.save( new Country( "British Indian Ocean Territory", "IO", "IOT", "Diego Garcia", "Africa", "Eastern Africa", 3000L, "https://restCountry.eu/data/iot.svg", "Africa") );
        repository.save( new Country( "United States Minor Outlying Islands", "UM", "UMI", "", "Americas", "Northern America", 300L, "https://restCountry.eu/data/umi.svg", "Americas") );
        repository.save( new Country( "Virgin Islands (British)", "VG", "VGB", "Road Town", "Americas", "Caribbean", 28514L, "https://restCountry.eu/data/vgb.svg", "Americas") );
        repository.save( new Country( "Virgin Islands (U.S.)", "VI", "VIR", "Charlotte Amalie", "Americas", "Caribbean", 114743L, "https://restCountry.eu/data/vir.svg", "Americas") );
        repository.save( new Country( "Brunei Darussalam", "BN", "BRN", "Bandar Seri Begawan", "Asia", "South-Eastern Asia", 411900L, "https://restCountry.eu/data/brn.svg", "Asia") );
        repository.save( new Country( "Bulgaria", "BG", "BGR", "Sofia", "Europe", "Eastern Europe", 7153784L, "https://restCountry.eu/data/bgr.svg", "Europe") );
        repository.save( new Country( "Burkina Faso", "BF", "BFA", "Ouagadougou", "Africa", "Western Africa", 19034397L, "https://restCountry.eu/data/bfa.svg", "Africa") );
        repository.save( new Country( "Burundi", "BI", "BDI", "Bujumbura", "Africa", "Eastern Africa", 10114505L, "https://restCountry.eu/data/bdi.svg", "Africa") );
        repository.save( new Country( "Cambodia", "KH", "KHM", "Phnom Penh", "Asia", "South-Eastern Asia", 15626444L, "https://restCountry.eu/data/khm.svg", "Asia") );
        repository.save( new Country( "Cameroon", "CM", "CMR", "YaoundÃ©", "Africa", "Middle Africa", 22709892L, "https://restCountry.eu/data/cmr.svg", "Africa") );
        repository.save( new Country( "Canada", "CA", "CAN", "Ottawa", "Americas", "Northern America", 36155487L, "https://restCountry.eu/data/can.svg", "Americas") );
        repository.save( new Country( "Cabo Verde", "CV", "CPV", "Praia", "Africa", "Western Africa", 531239L, "https://restCountry.eu/data/cpv.svg", "Africa") );
        repository.save( new Country( "Cayman Islands", "KY", "CYM", "George Town", "Americas", "Caribbean", 58238L, "https://restCountry.eu/data/cym.svg", "Americas") );
        repository.save( new Country( "Central African Republic", "CF", "CAF", "Bangui", "Africa", "Middle Africa", 4998000L, "https://restCountry.eu/data/caf.svg", "Africa") );
        repository.save( new Country( "Chad", "TD", "TCD", "N'Djamena", "Africa", "Middle Africa", 14497000L, "https://restCountry.eu/data/tcd.svg", "Africa") );
        repository.save( new Country( "Chile", "CL", "CHL", "Santiago", "Americas", "South America", 18191900L, "https://restCountry.eu/data/chl.svg", "Americas") );
        repository.save( new Country( "China", "CN", "CHN", "Beijing", "Asia", "Eastern Asia", 1377422166L, "https://restCountry.eu/data/chn.svg", "Asia") );
        repository.save( new Country( "Christmas Island", "CX", "CXR", "Flying Fish Cove", "Oceania", "Australia and New Zealand", 2072L, "https://restCountry.eu/data/cxr.svg", "Oceania") );
        repository.save( new Country( "Cocos (Keeling) Islands", "CC", "CCK", "West Island", "Oceania", "Australia and New Zealand", 550L, "https://restCountry.eu/data/cck.svg", "Oceania") );
        repository.save( new Country( "Colombia", "CO", "COL", "BogotÃ¡", "Americas", "South America", 48759958L, "https://restCountry.eu/data/col.svg", "Americas") );
        repository.save( new Country( "Comoros", "KM", "COM", "Moroni", "Africa", "Eastern Africa", 806153L, "https://restCountry.eu/data/com.svg", "Africa") );
        repository.save( new Country( "Congo", "CG", "COG", "Brazzaville", "Africa", "Middle Africa", 4741000L, "https://restCountry.eu/data/cog.svg", "Africa") );
        repository.save( new Country( "Congo (Democratic Republic of the)", "CD", "COD", "Kinshasa", "Africa", "Middle Africa", 85026000L, "https://restCountry.eu/data/cod.svg", "Africa") );
        repository.save( new Country( "Cook Islands", "CK", "COK", "Avarua", "Oceania", "Polynesia", 18100L, "https://restCountry.eu/data/cok.svg", "Oceania") );
        repository.save( new Country( "Costa Rica", "CR", "CRI", "San JosÃ©", "Americas", "Central America", 4890379L, "https://restCountry.eu/data/cri.svg", "Americas") );
        repository.save( new Country( "Croatia", "HR", "HRV", "Zagreb", "Europe", "Southern Europe", 4190669L, "https://restCountry.eu/data/hrv.svg", "Europe") );
        repository.save( new Country( "Cuba", "CU", "CUB", "Havana", "Americas", "Caribbean", 11239004L, "https://restCountry.eu/data/cub.svg", "Americas") );
        repository.save( new Country( "CuraÃ§ao", "CW", "CUW", "Willemstad", "Americas", "Caribbean", 154843L, "https://restCountry.eu/data/cuw.svg", "Americas") );
        repository.save( new Country( "Cyprus", "CY", "CYP", "Nicosia", "Europe", "Southern Europe", 847000L, "https://restCountry.eu/data/cyp.svg", "Europe") );
        repository.save( new Country( "Czech Republic", "CZ", "CZE", "Prague", "Europe", "Eastern Europe", 10558524L, "https://restCountry.eu/data/cze.svg", "Europe") );
        repository.save( new Country( "Denmark", "DK", "DNK", "Copenhagen", "Europe", "Northern Europe", 5717014L, "https://restCountry.eu/data/dnk.svg", "Europe") );
        repository.save( new Country( "Djibouti", "DJ", "DJI", "Djibouti", "Africa", "Eastern Africa", 900000L, "https://restCountry.eu/data/dji.svg", "Africa") );
        repository.save( new Country( "Dominica", "DM", "DMA", "Roseau", "Americas", "Caribbean", 71293L, "https://restCountry.eu/data/dma.svg", "Americas") );
        repository.save( new Country( "Dominican Republic", "DO", "DOM", "Santo Domingo", "Americas", "Caribbean", 10075045L, "https://restCountry.eu/data/dom.svg", "Americas") );
        repository.save( new Country( "Ecuador", "EC", "ECU", "Quito", "Americas", "South America", 16545799L, "https://restCountry.eu/data/ecu.svg", "Americas") );
        repository.save( new Country( "Egypt", "EG", "EGY", "Cairo", "Africa", "Northern Africa", 91290000L, "https://restCountry.eu/data/egy.svg", "Africa") );
        repository.save( new Country( "El Salvador", "SV", "SLV", "San Salvador", "Americas", "Central America", 6520675L, "https://restCountry.eu/data/slv.svg", "Americas") );
        repository.save( new Country( "Equatorial Guinea", "GQ", "GNQ", "Malabo", "Africa", "Middle Africa", 1222442L, "https://restCountry.eu/data/gnq.svg", "Africa") );
        repository.save( new Country( "Eritrea", "ER", "ERI", "Asmara", "Africa", "Eastern Africa", 5352000L, "https://restCountry.eu/data/eri.svg", "Africa") );
        repository.save( new Country( "Estonia", "EE", "EST", "Tallinn", "Europe", "Northern Europe", 1315944L, "https://restCountry.eu/data/est.svg", "Europe") );
        repository.save( new Country( "Ethiopia", "ET", "ETH", "Addis Ababa", "Africa", "Eastern Africa", 92206005L, "https://restCountry.eu/data/eth.svg", "Africa") );
        repository.save( new Country( "Falkland Islands (Malvinas)", "FK", "FLK", "Stanley", "Americas", "South America", 2563L, "https://restCountry.eu/data/flk.svg", "Americas") );
        repository.save( new Country( "Faroe Islands", "FO", "FRO", "TÃ³rshavn", "Europe", "Northern Europe", 49376L, "https://restCountry.eu/data/fro.svg", "Europe") );
        repository.save( new Country( "Fiji", "FJ", "FJI", "Suva", "Oceania", "Melanesia", 867000L, "https://restCountry.eu/data/fji.svg", "Oceania") );
        repository.save( new Country( "Finland", "FI", "FIN", "Helsinki", "Europe", "Northern Europe", 5491817L, "https://restCountry.eu/data/fin.svg", "Europe") );
        repository.save( new Country( "France", "FR", "FRA", "Paris", "Europe", "Western Europe", 66710000L, "https://restCountry.eu/data/fra.svg", "Europe") );
        repository.save( new Country( "French Guiana", "GF", "GUF", "Cayenne", "Americas", "South America", 254541L, "https://restCountry.eu/data/guf.svg", "Americas") );
        repository.save( new Country( "French Polynesia", "PF", "PYF", "PapeetÄ“", "Oceania", "Polynesia", 271800L, "https://restCountry.eu/data/pyf.svg", "Oceania") );
        repository.save( new Country( "French Southern Territories", "TF", "ATF", "Port-aux-FranÃ§ais", "Africa", "Southern Africa", 140L, "https://restCountry.eu/data/atf.svg", "Africa") );
        repository.save( new Country( "Gabon", "GA", "GAB", "Libreville", "Africa", "Middle Africa", 1802278L, "https://restCountry.eu/data/gab.svg", "Africa") );
        repository.save( new Country( "Gambia", "GM", "GMB", "Banjul", "Africa", "Western Africa", 1882450L, "https://restCountry.eu/data/gmb.svg", "Africa") );
        repository.save( new Country( "Georgia", "GE", "GEO", "Tbilisi", "Asia", "Western Asia", 3720400L, "https://restCountry.eu/data/geo.svg", "Asia") );
        repository.save( new Country( "Germany", "DE", "DEU", "Berlin", "Europe", "Western Europe", 81770900L, "https://restCountry.eu/data/deu.svg", "Europe") );
        repository.save( new Country( "Ghana", "GH", "GHA", "Accra", "Africa", "Western Africa", 27670174L, "https://restCountry.eu/data/gha.svg", "Africa") );
        repository.save( new Country( "Gibraltar", "GI", "GIB", "Gibraltar", "Europe", "Southern Europe", 33140L, "https://restCountry.eu/data/gib.svg", "Europe") );
        repository.save( new Country( "Greece", "GR", "GRC", "Athens", "Europe", "Southern Europe", 10858018L, "https://restCountry.eu/data/grc.svg", "Europe") );
        repository.save( new Country( "Greenland", "GL", "GRL", "Nuuk", "Americas", "Northern America", 55847L, "https://restCountry.eu/data/grl.svg", "Americas") );
        repository.save( new Country( "Grenada", "GD", "GRD", "St. George's", "Americas", "Caribbean", 103328L, "https://restCountry.eu/data/grd.svg", "Americas") );
        repository.save( new Country( "Guadeloupe", "GP", "GLP", "Basse-Terre", "Americas", "Caribbean", 400132L, "https://restCountry.eu/data/glp.svg", "Americas") );
        repository.save( new Country( "Guam", "GU", "GUM", "HagÃ¥tÃ±a", "Oceania", "Micronesia", 184200L, "https://restCountry.eu/data/gum.svg", "Oceania") );
        repository.save( new Country( "Guatemala", "GT", "GTM", "Guatemala City", "Americas", "Central America", 16176133L, "https://restCountry.eu/data/gtm.svg", "Americas") );
        repository.save( new Country( "Guernsey", "GG", "GGY", "St. Peter Port", "Europe", "Northern Europe", 62999L, "https://restCountry.eu/data/ggy.svg", "Europe") );
        repository.save( new Country( "Guinea", "GN", "GIN", "Conakry", "Africa", "Western Africa", 12947000L, "https://restCountry.eu/data/gin.svg", "Africa") );
        repository.save( new Country( "Guinea-Bissau", "GW", "GNB", "Bissau", "Africa", "Western Africa", 1547777L, "https://restCountry.eu/data/gnb.svg", "Africa") );
        repository.save( new Country( "Guyana", "GY", "GUY", "Georgetown", "Americas", "South America", 746900L, "https://restCountry.eu/data/guy.svg", "Americas") );
        repository.save( new Country( "Haiti", "HT", "HTI", "Port-au-Prince", "Americas", "Caribbean", 11078033L, "https://restCountry.eu/data/hti.svg", "Americas") );
        repository.save( new Country( "Heard Island and McDonald Islands", "HM", "HMD", "", "", "", 0L, "https://restCountry.eu/data/hmd.svg", "") );
        repository.save( new Country( "Holy See", "VA", "VAT", "Rome", "Europe", "Southern Europe", 451L, "https://restCountry.eu/data/vat.svg", "Europe") );
        repository.save( new Country( "Honduras", "HN", "HND", "Tegucigalpa", "Americas", "Central America", 8576532L, "https://restCountry.eu/data/hnd.svg", "Americas") );
        repository.save( new Country( "Hong Kong", "HK", "HKG", "City of Victoria", "Asia", "Eastern Asia", 7324300L, "https://restCountry.eu/data/hkg.svg", "Asia") );
        repository.save( new Country( "Hungary", "HU", "HUN", "Budapest", "Europe", "Eastern Europe", 9823000L, "https://restCountry.eu/data/hun.svg", "Europe") );
        repository.save( new Country( "Iceland", "IS", "ISL", "ReykjavÃ­k", "Europe", "Northern Europe", 334300L, "https://restCountry.eu/data/isl.svg", "Europe") );
        repository.save( new Country( "India", "IN", "IND", "New Delhi", "Asia", "Southern Asia", 1295210000L, "https://restCountry.eu/data/ind.svg", "Asia") );
        repository.save( new Country( "Indonesia", "ID", "IDN", "Jakarta", "Asia", "South-Eastern Asia", 258705000L, "https://restCountry.eu/data/idn.svg", "Asia") );
        repository.save( new Country( "CÃ´te d'Ivoire", "CI", "CIV", "Yamoussoukro", "Africa", "Western Africa", 22671331L, "https://restCountry.eu/data/civ.svg", "Africa") );
        repository.save( new Country( "Iran (Islamic Republic of)", "IR", "IRN", "Tehran", "Asia", "Southern Asia", 79369900L, "https://restCountry.eu/data/irn.svg", "Asia") );
        repository.save( new Country( "Iraq", "IQ", "IRQ", "Baghdad", "Asia", "Western Asia", 37883543L, "https://restCountry.eu/data/irq.svg", "Asia") );
        repository.save( new Country( "Ireland", "IE", "IRL", "Dublin", "Europe", "Northern Europe", 6378000L, "https://restCountry.eu/data/irl.svg", "Europe") );
        repository.save( new Country( "Isle of Man", "IM", "IMN", "Douglas", "Europe", "Northern Europe", 84497L, "https://restCountry.eu/data/imn.svg", "Europe") );
        repository.save( new Country( "Israel", "IL", "ISR", "Jerusalem", "Asia", "Western Asia", 8527400L, "https://restCountry.eu/data/isr.svg", "Asia") );
        repository.save( new Country( "Italy", "IT", "ITA", "Rome", "Europe", "Southern Europe", 60665551L, "https://restCountry.eu/data/ita.svg", "Europe") );
        repository.save( new Country( "Jamaica", "JM", "JAM", "Kingston", "Americas", "Caribbean", 2723246L, "https://restCountry.eu/data/jam.svg", "Americas") );
        repository.save( new Country( "Japan", "JP", "JPN", "Tokyo", "Asia", "Eastern Asia", 126960000L, "https://restCountry.eu/data/jpn.svg", "Asia") );
        repository.save( new Country( "Jersey", "JE", "JEY", "Saint Helier", "Europe", "Northern Europe", 100800L, "https://restCountry.eu/data/jey.svg", "Europe") );
        repository.save( new Country( "Jordan", "JO", "JOR", "Amman", "Asia", "Western Asia", 9531712L, "https://restCountry.eu/data/jor.svg", "Asia") );
        repository.save( new Country( "Kazakhstan", "KZ", "KAZ", "Astana", "Asia", "Central Asia", 17753200L, "https://restCountry.eu/data/kaz.svg", "Asia") );
        repository.save( new Country( "Kenya", "KE", "KEN", "Nairobi", "Africa", "Eastern Africa", 47251000L, "https://restCountry.eu/data/ken.svg", "Africa") );
        repository.save( new Country( "Kiribati", "KI", "KIR", "South Tarawa", "Oceania", "Micronesia", 113400L, "https://restCountry.eu/data/kir.svg", "Oceania") );
        repository.save( new Country( "Kuwait", "KW", "KWT", "Kuwait City", "Asia", "Western Asia", 4183658L, "https://restCountry.eu/data/kwt.svg", "Asia") );
        repository.save( new Country( "Kyrgyzstan", "KG", "KGZ", "Bishkek", "Asia", "Central Asia", 6047800L, "https://restCountry.eu/data/kgz.svg", "Asia") );
        repository.save( new Country( "Lao People's Democratic Republic", "LA", "LAO", "Vientiane", "Asia", "South-Eastern Asia", 6492400L, "https://restCountry.eu/data/lao.svg", "Asia") );
        repository.save( new Country( "Latvia", "LV", "LVA", "Riga", "Europe", "Northern Europe", 1961600L, "https://restCountry.eu/data/lva.svg", "Europe") );
        repository.save( new Country( "Lebanon", "LB", "LBN", "Beirut", "Asia", "Western Asia", 5988000L, "https://restCountry.eu/data/lbn.svg", "Asia") );
        repository.save( new Country( "Lesotho", "LS", "LSO", "Maseru", "Africa", "Southern Africa", 1894194L, "https://restCountry.eu/data/lso.svg", "Africa") );
        repository.save( new Country( "Liberia", "LR", "LBR", "Monrovia", "Africa", "Western Africa", 4615000L, "https://restCountry.eu/data/lbr.svg", "Africa") );
        repository.save( new Country( "Libya", "LY", "LBY", "Tripoli", "Africa", "Northern Africa", 6385000L, "https://restCountry.eu/data/lby.svg", "Africa") );
        repository.save( new Country( "Liechtenstein", "LI", "LIE", "Vaduz", "Europe", "Western Europe", 37623L, "https://restCountry.eu/data/lie.svg", "Europe") );
        repository.save( new Country( "Lithuania", "LT", "LTU", "Vilnius", "Europe", "Northern Europe", 2872294L, "https://restCountry.eu/data/ltu.svg", "Europe") );
        repository.save( new Country( "Luxembourg", "LU", "LUX", "Luxembourg", "Europe", "Western Europe", 576200L, "https://restCountry.eu/data/lux.svg", "Europe") );
        repository.save( new Country( "Macao", "MO", "MAC", "", "Asia", "Eastern Asia", 649100L, "https://restCountry.eu/data/mac.svg", "Asia") );
        repository.save( new Country( "Macedonia (the former Yugoslav Republic of)", "MK", "MKD", "Skopje", "Europe", "Southern Europe", 2058539L, "https://restCountry.eu/data/mkd.svg", "Europe") );
        repository.save( new Country( "Madagascar", "MG", "MDG", "Antananarivo", "Africa", "Eastern Africa", 22434363L, "https://restCountry.eu/data/mdg.svg", "Africa") );
        repository.save( new Country( "Malawi", "MW", "MWI", "Lilongwe", "Africa", "Eastern Africa", 16832910L, "https://restCountry.eu/data/mwi.svg", "Africa") );
        repository.save( new Country( "Malaysia", "MY", "MYS", "Kuala Lumpur", "Asia", "South-Eastern Asia", 31405416L, "https://restCountry.eu/data/mys.svg", "Asia") );
        repository.save( new Country( "Maldives", "MV", "MDV", "MalÃ©", "Asia", "Southern Asia", 344023L, "https://restCountry.eu/data/mdv.svg", "Asia") );
        repository.save( new Country( "Mali", "ML", "MLI", "Bamako", "Africa", "Western Africa", 18135000L, "https://restCountry.eu/data/mli.svg", "Africa") );
        repository.save( new Country( "Malta", "MT", "MLT", "Valletta", "Europe", "Southern Europe", 425384L, "https://restCountry.eu/data/mlt.svg", "Europe") );
        repository.save( new Country( "Marshall Islands", "MH", "MHL", "Majuro", "Oceania", "Micronesia", 54880L, "https://restCountry.eu/data/mhl.svg", "Oceania") );
        repository.save( new Country( "Martinique", "MQ", "MTQ", "Fort-de-France", "Americas", "Caribbean", 378243L, "https://restCountry.eu/data/mtq.svg", "Americas") );
        repository.save( new Country( "Mauritania", "MR", "MRT", "Nouakchott", "Africa", "Western Africa", 3718678L, "https://restCountry.eu/data/mrt.svg", "Africa") );
        repository.save( new Country( "Mauritius", "MU", "MUS", "Port Louis", "Africa", "Eastern Africa", 1262879L, "https://restCountry.eu/data/mus.svg", "Africa") );
        repository.save( new Country( "Mayotte", "YT", "MYT", "Mamoudzou", "Africa", "Eastern Africa", 226915L, "https://restCountry.eu/data/myt.svg", "Africa") );
        repository.save( new Country( "Mexico", "MX", "MEX", "Mexico City", "Americas", "Central America", 122273473L, "https://restCountry.eu/data/mex.svg", "Americas") );
        repository.save( new Country( "Micronesia (Federated States of)", "FM", "FSM", "Palikir", "Oceania", "Micronesia", 102800L, "https://restCountry.eu/data/fsm.svg", "Oceania") );
        repository.save( new Country( "Moldova (Republic of)", "MD", "MDA", "ChiÈ™inÄƒu", "Europe", "Eastern Europe", 3553100L, "https://restCountry.eu/data/mda.svg", "Europe") );
        repository.save( new Country( "Monaco", "MC", "MCO", "Monaco", "Europe", "Western Europe", 38400L, "https://restCountry.eu/data/mco.svg", "Europe") );
        repository.save( new Country( "Mongolia", "MN", "MNG", "Ulan Bator", "Asia", "Eastern Asia", 3093100L, "https://restCountry.eu/data/mng.svg", "Asia") );
        repository.save( new Country( "Montenegro", "ME", "MNE", "Podgorica", "Europe", "Southern Europe", 621810L, "https://restCountry.eu/data/mne.svg", "Europe") );
        repository.save( new Country( "Montserrat", "MS", "MSR", "Plymouth", "Americas", "Caribbean", 4922L, "https://restCountry.eu/data/msr.svg", "Americas") );
        repository.save( new Country( "Morocco", "MA", "MAR", "Rabat", "Africa", "Northern Africa", 33337529L, "https://restCountry.eu/data/mar.svg", "Africa") );
        repository.save( new Country( "Mozambique", "MZ", "MOZ", "Maputo", "Africa", "Eastern Africa", 26423700L, "https://restCountry.eu/data/moz.svg", "Africa") );
        repository.save( new Country( "Myanmar", "MM", "MMR", "Naypyidaw", "Asia", "South-Eastern Asia", 51419420L, "https://restCountry.eu/data/mmr.svg", "Asia") );
        repository.save( new Country( "Namibia", "NA", "NAM", "Windhoek", "Africa", "Southern Africa", 2324388L, "https://restCountry.eu/data/nam.svg", "Africa") );
        repository.save( new Country( "Nauru", "NR", "NRU", "Yaren", "Oceania", "Micronesia", 10084L, "https://restCountry.eu/data/nru.svg", "Oceania") );
        repository.save( new Country( "Nepal", "NP", "NPL", "Kathmandu", "Asia", "Southern Asia", 28431500L, "https://restCountry.eu/data/npl.svg", "Asia") );
        repository.save( new Country( "Netherlands", "NL", "NLD", "Amsterdam", "Europe", "Western Europe", 17019800L, "https://restCountry.eu/data/nld.svg", "Europe") );
        repository.save( new Country( "New Caledonia", "NC", "NCL", "NoumÃ©a", "Oceania", "Melanesia", 268767L, "https://restCountry.eu/data/ncl.svg", "Oceania") );
        repository.save( new Country( "New Zealand", "NZ", "NZL", "Wellington", "Oceania", "Australia and New Zealand", 4697854L, "https://restCountry.eu/data/nzl.svg", "Oceania") );
        repository.save( new Country( "Nicaragua", "NI", "NIC", "Managua", "Americas", "Central America", 6262703L, "https://restCountry.eu/data/nic.svg", "Americas") );
        repository.save( new Country( "Niger", "NE", "NER", "Niamey", "Africa", "Western Africa", 20715000L, "https://restCountry.eu/data/ner.svg", "Africa") );
        repository.save( new Country( "Nigeria", "NG", "NGA", "Abuja", "Africa", "Western Africa", 186988000L, "https://restCountry.eu/data/nga.svg", "Africa") );
        repository.save( new Country( "Niue", "NU", "NIU", "Alofi", "Oceania", "Polynesia", 1470L, "https://restCountry.eu/data/niu.svg", "Oceania") );
        repository.save( new Country( "Norfolk Island", "NF", "NFK", "Kingston", "Oceania", "Australia and New Zealand", 2302L, "https://restCountry.eu/data/nfk.svg", "Oceania") );
        repository.save( new Country( "Korea (Democratic People's Republic of)", "KP", "PRK", "Pyongyang", "Asia", "Eastern Asia", 25281000L, "https://restCountry.eu/data/prk.svg", "Asia") );
        repository.save( new Country( "Northern Mariana Islands", "MP", "MNP", "Saipan", "Oceania", "Micronesia", 56940L, "https://restCountry.eu/data/mnp.svg", "Oceania") );
        repository.save( new Country( "Norway", "NO", "NOR", "Oslo", "Europe", "Northern Europe", 5223256L, "https://restCountry.eu/data/nor.svg", "Europe") );
        repository.save( new Country( "Oman", "OM", "OMN", "Muscat", "Asia", "Western Asia", 4420133L, "https://restCountry.eu/data/omn.svg", "Asia") );
        repository.save( new Country( "Pakistan", "PK", "PAK", "Islamabad", "Asia", "Southern Asia", 194125062L, "https://restCountry.eu/data/pak.svg", "Asia") );
        repository.save( new Country( "Palau", "PW", "PLW", "Ngerulmud", "Oceania", "Micronesia", 17950L, "https://restCountry.eu/data/plw.svg", "Oceania") );
        repository.save( new Country( "Palestine, State of", "PS", "PSE", "Ramallah", "Asia", "Western Asia", 4682467L, "https://restCountry.eu/data/pse.svg", "Asia") );
        repository.save( new Country( "Panama", "PA", "PAN", "Panama City", "Americas", "Central America", 3814672L, "https://restCountry.eu/data/pan.svg", "Americas") );
        repository.save( new Country( "Papua New Guinea", "PG", "PNG", "Port Moresby", "Oceania", "Melanesia", 8083700L, "https://restCountry.eu/data/png.svg", "Oceania") );
        repository.save( new Country( "Paraguay", "PY", "PRY", "AsunciÃ³n", "Americas", "South America", 6854536L, "https://restCountry.eu/data/pry.svg", "Americas") );
        repository.save( new Country( "Peru", "PE", "PER", "Lima", "Americas", "South America", 31488700L, "https://restCountry.eu/data/per.svg", "Americas") );
        repository.save( new Country( "Philippines", "PH", "PHL", "Manila", "Asia", "South-Eastern Asia", 103279800L, "https://restCountry.eu/data/phl.svg", "Asia") );
        repository.save( new Country( "Pitcairn", "PN", "PCN", "Adamstown", "Oceania", "Polynesia", 56L, "https://restCountry.eu/data/pcn.svg", "Oceania") );
        repository.save( new Country( "Poland", "PL", "POL", "Warsaw", "Europe", "Eastern Europe", 38437239L, "https://restCountry.eu/data/pol.svg", "Europe") );
        repository.save( new Country( "Portugal", "PT", "PRT", "Lisbon", "Europe", "Southern Europe", 10374822L, "https://restCountry.eu/data/prt.svg", "Europe") );
        repository.save( new Country( "Puerto Rico", "PR", "PRI", "San Juan", "Americas", "Caribbean", 3474182L, "https://restCountry.eu/data/pri.svg", "Americas") );
        repository.save( new Country( "Qatar", "QA", "QAT", "Doha", "Asia", "Western Asia", 2587564L, "https://restCountry.eu/data/qat.svg", "Asia") );
        repository.save( new Country( "Republic of Kosovo", "XK", "KOS", "Pristina", "Europe", "Eastern Europe", 1733842L, "https://restCountry.eu/data/kos.svg", "Europe") );
        repository.save( new Country( "RÃ©union", "RE", "REU", "Saint-Denis", "Africa", "Eastern Africa", 840974L, "https://restCountry.eu/data/reu.svg", "Africa") );
        repository.save( new Country( "Romania", "RO", "ROU", "Bucharest", "Europe", "Eastern Europe", 19861408L, "https://restCountry.eu/data/rou.svg", "Europe") );
        repository.save( new Country( "Russian Federation", "RU", "RUS", "Moscow", "Europe", "Eastern Europe", 146599183L, "https://restCountry.eu/data/rus.svg", "Europe") );
        repository.save( new Country( "Rwanda", "RW", "RWA", "Kigali", "Africa", "Eastern Africa", 11553188L, "https://restCountry.eu/data/rwa.svg", "Africa") );
        repository.save( new Country( "Saint BarthÃ©lemy", "BL", "BLM", "Gustavia", "Americas", "Caribbean", 9417L, "https://restCountry.eu/data/blm.svg", "Americas") );
        repository.save( new Country( "Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", "Jamestown", "Africa", "Western Africa", 4255L, "https://restCountry.eu/data/shn.svg", "Africa") );
        repository.save( new Country( "Saint Kitts and Nevis", "KN", "KNA", "Basseterre", "Americas", "Caribbean", 46204L, "https://restCountry.eu/data/kna.svg", "Americas") );
        repository.save( new Country( "Saint Lucia", "LC", "LCA", "Castries", "Americas", "Caribbean", 186000L, "https://restCountry.eu/data/lca.svg", "Americas") );
        repository.save( new Country( "Saint Martin (French part)", "MF", "MAF", "Marigot", "Americas", "Caribbean", 36979L, "https://restCountry.eu/data/maf.svg", "Americas") );
        repository.save( new Country( "Saint Pierre and Miquelon", "PM", "SPM", "Saint-Pierre", "Americas", "Northern America", 6069L, "https://restCountry.eu/data/spm.svg", "Americas") );
        repository.save( new Country( "Saint Vincent and the Grenadines", "VC", "VCT", "Kingstown", "Americas", "Caribbean", 109991L, "https://restCountry.eu/data/vct.svg", "Americas") );
        repository.save( new Country( "Samoa", "WS", "WSM", "Apia", "Oceania", "Polynesia", 194899L, "https://restCountry.eu/data/wsm.svg", "Oceania") );
        repository.save( new Country( "San Marino", "SM", "SMR", "City of San Marino", "Europe", "Southern Europe", 33005L, "https://restCountry.eu/data/smr.svg", "Europe") );
        repository.save( new Country( "Sao Tome and Principe", "ST", "STP", "SÃ£o TomÃ©", "Africa", "Middle Africa", 187356L, "https://restCountry.eu/data/stp.svg", "Africa") );
        repository.save( new Country( "Saudi Arabia", "SA", "SAU", "Riyadh", "Asia", "Western Asia", 32248200L, "https://restCountry.eu/data/sau.svg", "Asia") );
        repository.save( new Country( "Senegal", "SN", "SEN", "Dakar", "Africa", "Western Africa", 14799859L, "https://restCountry.eu/data/sen.svg", "Africa") );
        repository.save( new Country( "Serbia", "RS", "SRB", "Belgrade", "Europe", "Southern Europe", 7076372L, "https://restCountry.eu/data/srb.svg", "Europe") );
        repository.save( new Country( "Seychelles", "SC", "SYC", "Victoria", "Africa", "Eastern Africa", 91400L, "https://restCountry.eu/data/syc.svg", "Africa") );
        repository.save( new Country( "Sierra Leone", "SL", "SLE", "Freetown", "Africa", "Western Africa", 7075641L, "https://restCountry.eu/data/sle.svg", "Africa") );
        repository.save( new Country( "Singapore", "SG", "SGP", "Singapore", "Asia", "South-Eastern Asia", 5535000L, "https://restCountry.eu/data/sgp.svg", "Asia") );
        repository.save( new Country( "Sint Maarten (Dutch part)", "SX", "SXM", "Philipsburg", "Americas", "Caribbean", 38247L, "https://restCountry.eu/data/sxm.svg", "Americas") );
        repository.save( new Country( "Slovakia", "SK", "SVK", "Bratislava", "Europe", "Eastern Europe", 5426252L, "https://restCountry.eu/data/svk.svg", "Europe") );
        repository.save( new Country( "Slovenia", "SI", "SVN", "Ljubljana", "Europe", "Southern Europe", 2064188L, "https://restCountry.eu/data/svn.svg", "Europe") );
        repository.save( new Country( "Solomon Islands", "SB", "SLB", "Honiara", "Oceania", "Melanesia", 642000L, "https://restCountry.eu/data/slb.svg", "Oceania") );
        repository.save( new Country( "Somalia", "SO", "SOM", "Mogadishu", "Africa", "Eastern Africa", 11079000L, "https://restCountry.eu/data/som.svg", "Africa") );
        repository.save( new Country( "South Africa", "ZA", "ZAF", "Pretoria", "Africa", "Southern Africa", 55653654L, "https://restCountry.eu/data/zaf.svg", "Africa") );
        repository.save( new Country( "South Georgia and the South Sandwich Islands", "GS", "SGS", "King Edward Point", "Americas", "South America", 30L, "https://restCountry.eu/data/sgs.svg", "Americas") );
        repository.save( new Country( "Korea (Republic of)", "KR", "KOR", "Seoul", "Asia", "Eastern Asia", 50801405L, "https://restCountry.eu/data/kor.svg", "Asia") );
        repository.save( new Country( "South Sudan", "SS", "SSD", "Juba", "Africa", "Middle Africa", 12131000L, "https://restCountry.eu/data/ssd.svg", "Africa") );
        repository.save( new Country( "Spain", "ES", "ESP", "Madrid", "Europe", "Southern Europe", 46438422L, "https://restCountry.eu/data/esp.svg", "Europe") );
        repository.save( new Country( "Sri Lanka", "LK", "LKA", "Colombo", "Asia", "Southern Asia", 20966000L, "https://restCountry.eu/data/lka.svg", "Asia") );
        repository.save( new Country( "Sudan", "SD", "SDN", "Khartoum", "Africa", "Northern Africa", 39598700L, "https://restCountry.eu/data/sdn.svg", "Africa") );
        repository.save( new Country( "Suriname", "SR", "SUR", "Paramaribo", "Americas", "South America", 541638L, "https://restCountry.eu/data/sur.svg", "Americas") );
        repository.save( new Country( "Svalbard and Jan Mayen", "SJ", "SJM", "Longyearbyen", "Europe", "Northern Europe", 2562L, "https://restCountry.eu/data/sjm.svg", "Europe") );
        repository.save( new Country( "Swaziland", "SZ", "SWZ", "Lobamba", "Africa", "Southern Africa", 1132657L, "https://restCountry.eu/data/swz.svg", "Africa") );
        repository.save( new Country( "Sweden", "SE", "SWE", "Stockholm", "Europe", "Northern Europe", 9894888L, "https://restCountry.eu/data/swe.svg", "Europe") );
        repository.save( new Country( "Switzerland", "CH", "CHE", "Bern", "Europe", "Western Europe", 8341600L, "https://restCountry.eu/data/che.svg", "Europe") );
        repository.save( new Country( "Syrian Arab Republic", "SY", "SYR", "Damascus", "Asia", "Western Asia", 18564000L, "https://restCountry.eu/data/syr.svg", "Asia") );
        repository.save( new Country( "Taiwan", "TW", "TWN", "Taipei", "Asia", "Eastern Asia", 23503349L, "https://restCountry.eu/data/twn.svg", "Asia") );
        repository.save( new Country( "Tajikistan", "TJ", "TJK", "Dushanbe", "Asia", "Central Asia", 8593600L, "https://restCountry.eu/data/tjk.svg", "Asia") );
        repository.save( new Country( "Tanzania, United Republic of", "TZ", "TZA", "Dodoma", "Africa", "Eastern Africa", 55155000L, "https://restCountry.eu/data/tza.svg", "Africa") );
        repository.save( new Country( "Thailand", "TH", "THA", "Bangkok", "Asia", "South-Eastern Asia", 65327652L, "https://restCountry.eu/data/tha.svg", "Asia") );
        repository.save( new Country( "Timor-Leste", "TL", "TLS", "Dili", "Asia", "South-Eastern Asia", 1167242L, "https://restCountry.eu/data/tls.svg", "Asia") );
        repository.save( new Country( "Togo", "TG", "TGO", "LomÃ©", "Africa", "Western Africa", 7143000L, "https://restCountry.eu/data/tgo.svg", "Africa") );
        repository.save( new Country( "Tokelau", "TK", "TKL", "Fakaofo", "Oceania", "Polynesia", 1411L, "https://restCountry.eu/data/tkl.svg", "Oceania") );
        repository.save( new Country( "Tonga", "TO", "TON", "Nuku'alofa", "Oceania", "Polynesia", 103252L, "https://restCountry.eu/data/ton.svg", "Oceania") );
        repository.save( new Country( "Trinidad and Tobago", "TT", "TTO", "Port of Spain", "Americas", "Caribbean", 1349667L, "https://restCountry.eu/data/tto.svg", "Americas") );
        repository.save( new Country( "Tunisia", "TN", "TUN", "Tunis", "Africa", "Northern Africa", 11154400L, "https://restCountry.eu/data/tun.svg", "Africa") );
        repository.save( new Country( "Turkey", "TR", "TUR", "Ankara", "Asia", "Western Asia", 78741053L, "https://restCountry.eu/data/tur.svg", "Asia") );
        repository.save( new Country( "Turkmenistan", "TM", "TKM", "Ashgabat", "Asia", "Central Asia", 4751120L, "https://restCountry.eu/data/tkm.svg", "Asia") );
        repository.save( new Country( "Turks and Caicos Islands", "TC", "TCA", "Cockburn Town", "Americas", "Caribbean", 31458L, "https://restCountry.eu/data/tca.svg", "Americas") );
        repository.save( new Country( "Tuvalu", "TV", "TUV", "Funafuti", "Oceania", "Polynesia", 10640L, "https://restCountry.eu/data/tuv.svg", "Oceania") );
        repository.save( new Country( "Uganda", "UG", "UGA", "Kampala", "Africa", "Eastern Africa", 33860700L, "https://restCountry.eu/data/uga.svg", "Africa") );
        repository.save( new Country( "Ukraine", "UA", "UKR", "Kiev", "Europe", "Eastern Europe", 42692393L, "https://restCountry.eu/data/ukr.svg", "Europe") );
        repository.save( new Country( "United Arab Emirates", "AE", "ARE", "Abu Dhabi", "Asia", "Western Asia", 9856000L, "https://restCountry.eu/data/are.svg", "Asia") );
        repository.save( new Country( "United Kingdom of Great Britain and Northern Ireland", "GB", "GBR", "London", "Europe", "Northern Europe", 65110000L, "https://restCountry.eu/data/gbr.svg", "Europe") );
        repository.save( new Country( "United States of America", "US", "USA", "Washington, D.C.", "Americas", "Northern America", 323947000L, "https://restCountry.eu/data/usa.svg", "Americas") );
        repository.save( new Country( "Uruguay", "UY", "URY", "Montevideo", "Americas", "South America", 3480222L, "https://restCountry.eu/data/ury.svg", "Americas") );
        repository.save( new Country( "Uzbekistan", "UZ", "UZB", "Tashkent", "Asia", "Central Asia", 31576400L, "https://restCountry.eu/data/uzb.svg", "Asia") );
        repository.save( new Country( "Vanuatu", "VU", "VUT", "Port Vila", "Oceania", "Melanesia", 277500L, "https://restCountry.eu/data/vut.svg", "Oceania") );
        repository.save( new Country( "Venezuela (Bolivarian Republic of)", "VE", "VEN", "Caracas", "Americas", "South America", 31028700L, "https://restCountry.eu/data/ven.svg", "Americas") );
        repository.save( new Country( "Viet Nam", "VN", "VNM", "Hanoi", "Asia", "South-Eastern Asia", 92700000L, "https://restCountry.eu/data/vnm.svg", "Asia") );
        repository.save( new Country( "Wallis and Futuna", "WF", "WLF", "Mata-Utu", "Oceania", "Polynesia", 11750L, "https://restCountry.eu/data/wlf.svg", "Oceania") );
        repository.save( new Country( "Western Sahara", "EH", "ESH", "El AaiÃºn", "Africa", "Northern Africa", 510713L, "https://restCountry.eu/data/esh.svg", "Africa") );
        repository.save( new Country( "Yemen", "YE", "YEM", "Sana'a", "Asia", "Western Asia", 27478000L, "https://restCountry.eu/data/yem.svg", "Asia") );
        repository.save( new Country( "Zambia", "ZM", "ZMB", "Lusaka", "Africa", "Eastern Africa", 15933883L, "https://restCountry.eu/data/zmb.svg", "Africa") );
        repository.save( new Country( "Zimbabwe", "ZW", "ZWE", "Harare", "Africa", "Eastern Africa", 14240168L, "https://restCountry.eu/data/zwe.svg", "Africa") );



    }

}